version: '3.8'

services:
  # Database Service (same as production)
  database:
    image: mariadb:10.11
    container_name: videoforge_db_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-video_forge}
      MYSQL_USER: ${DB_USER:-video_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-videopassword}
    volumes:
      - db_data_dev:/var/lib/mysql
      - ./server/src/scripts/db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - videoforge_network
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Server Service (development with hot reloading)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: videoforge_server_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 8000
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-video_forge}
      DB_USER: ${DB_USER:-video_user}
      DB_PASSWORD: ${DB_PASSWORD:-videopassword}
      JWT_SECRET: ${JWT_SECRET:-dev_jwt_secret_not_for_production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      PROCESSING_INPUT_DIR: /app/data/inputs
      PROCESSING_OUTPUT_DIR: /app/data/outputs
      PROCESSING_TEMP_DIR: /app/data/temp
      MAX_CONCURRENT_JOBS: ${MAX_CONCURRENT_JOBS:-6}
      PIXABAY_API_KEY: ${PIXABAY_API_KEY:-your_pixabay_api_key}
      
    volumes:
      # Mount source code for development
      - ./server/src:/app/src:ro
      - ./server/package.json:/app/package.json:ro
      - server_data_dev:/app/data
    networks:
      - videoforge_network
    ports:
      - "${SERVER_PORT:-8000}:8000"
    depends_on:
      database:
        condition: service_healthy
    command: node src/server.js

networks:
  videoforge_network:
    driver: bridge

volumes:
  db_data_dev:
    driver: local
  server_data_dev:
    driver: local