version: '3.8'

services:
  # Server Service (Local Development - Build from source)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: videoforge_server_dev
    restart: unless-stopped
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      PORT: 8000
    volumes:
      # Mount source code for development (hot reload)
      - ./server:/app
      - /app/node_modules
    networks:
      - videoforge_network
    ports:
      - "${SERVER_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: npm run dev

  # Client Service (Local Development - Build from source)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    platform: linux/amd64
    container_name: videoforge_client_dev
    restart: unless-stopped
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      REACT_APP_API_BASE_URL: http://localhost:8000/api
      REACT_APP_SERVER_URL: http://localhost:8000
    volumes:
      # Mount source code for development (hot reload)
      - ./client:/app
      - /app/node_modules
    networks:
      - videoforge_network
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - server

networks:
  videoforge_network:
    driver: bridge