AWSTemplateFormatVersion: '2010-09-09'
Description: 'VideoForge - ECS Fargate Services (Auth and Management)'

Parameters:
  EnvironmentName:
    Description: Environment name prefix
    Type: String
    Default: video-forge

  StudentID:
    Description: Student ID for naming
    Type: String
    Default: n12159069

  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

  PublicSubnetIds:
    Description: Comma-separated list of public subnet IDs
    Type: List<AWS::EC2::Subnet::Id>

  PrivateSubnetIds:
    Description: Comma-separated list of private subnet IDs
    Type: List<AWS::EC2::Subnet::Id>

  ECSSecurityGroupId:
    Description: Security group ID for ECS tasks
    Type: AWS::EC2::SecurityGroup::Id

  ECSTaskExecutionRoleArn:
    Description: ARN of ECS Task Execution Role
    Type: String

  ECSTaskRoleArn:
    Description: ARN of ECS Task Role
    Type: String

  ECRAccountId:
    Description: AWS Account ID for ECR
    Type: String
    Default: '901444280953'

  ECRRegion:
    Description: AWS Region for ECR
    Type: String
    Default: ap-southeast-2

  # Database Configuration
  DBHost:
    Description: RDS database host
    Type: String

  DBPort:
    Description: RDS database port
    Type: String
    Default: '5432'

  DBName:
    Description: RDS database name
    Type: String
    Default: cohort_2025

  DBUser:
    Description: RDS database username
    Type: String
    Default: s458

  DBSecretArn:
    Description: ARN of database credentials secret in Secrets Manager
    Type: String

  # S3 Configuration
  S3BucketName:
    Description: S3 bucket name
    Type: String
    Default: video-forge-storage

  # Cognito Configuration
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Type: String

  CognitoClientId:
    Description: Cognito Client ID
    Type: String

  JWTSecretArn:
    Description: ARN of JWT secret in Secrets Manager
    Type: String

Resources:
  # ============================================
  # ECS Cluster
  # ============================================
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${StudentID}-${EnvironmentName}-cluster'
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
          Base: 1
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-ecs-cluster'
        - Key: Environment
          Value: production
        - Key: ManagedBy
          Value: CloudFormation

  # ============================================
  # CloudWatch Log Groups
  # ============================================
  AuthServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${EnvironmentName}/auth-service'
      RetentionInDays: 7

  ManagementServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${EnvironmentName}/management-service'
      RetentionInDays: 7

  # ============================================
  # Auth Service Task Definition
  # ============================================
  AuthServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${EnvironmentName}-auth-service'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn
      TaskRoleArn: !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: auth-service
          Image: !Sub '${ECRAccountId}.dkr.ecr.${ECRRegion}.amazonaws.com/video-forge-auth-service:latest'
          Essential: true
          PortMappings:
            - ContainerPort: 5000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: PORT
              Value: '5000'
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
            - Name: DB_HOST
              Value: !Ref DBHost
            - Name: DB_PORT
              Value: !Ref DBPort
            - Name: DB_NAME
              Value: !Ref DBName
            - Name: DB_USER
              Value: !Ref DBUser
            - Name: S3_BUCKET_NAME
              Value: !Ref S3BucketName
            - Name: COGNITO_USER_POOL_ID
              Value: !Ref CognitoUserPoolId
            - Name: COGNITO_CLIENT_ID
              Value: !Ref CognitoClientId
          Secrets:
            - Name: DB_PASSWORD
              ValueFrom: !Sub '${DBSecretArn}:password::'
            - Name: JWT_SECRET
              ValueFrom: !Ref JWTSecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AuthServiceLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: auth-service
          HealthCheck:
            Command:
              - CMD-SHELL
              - wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-auth-service-task'
        - Key: Environment
          Value: production

  # ============================================
  # Management Service Task Definition
  # ============================================
  ManagementServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${EnvironmentName}-management-service'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn
      TaskRoleArn: !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: management-service
          Image: !Sub '${ECRAccountId}.dkr.ecr.${ECRRegion}.amazonaws.com/video-forge-management-service:latest'
          Essential: true
          PortMappings:
            - ContainerPort: 5002
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: PORT
              Value: '5002'
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
            - Name: DB_HOST
              Value: !Ref DBHost
            - Name: DB_PORT
              Value: !Ref DBPort
            - Name: DB_NAME
              Value: !Ref DBName
            - Name: DB_USER
              Value: !Ref DBUser
            - Name: S3_BUCKET_NAME
              Value: !Ref S3BucketName
            - Name: COGNITO_USER_POOL_ID
              Value: !Ref CognitoUserPoolId
            - Name: COGNITO_CLIENT_ID
              Value: !Ref CognitoClientId
          Secrets:
            - Name: DB_PASSWORD
              ValueFrom: !Sub '${DBSecretArn}:password::'
            - Name: JWT_SECRET
              ValueFrom: !Ref JWTSecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ManagementServiceLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: management-service
          HealthCheck:
            Command:
              - CMD-SHELL
              - wget --no-verbose --tries=1 --spider http://localhost:5002/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-management-service-task'
        - Key: Environment
          Value: production

  # ============================================
  # Auth Service
  # ============================================
  AuthService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: auth-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref AuthServiceTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PublicSubnetIds
          SecurityGroups:
            - !Ref ECSSecurityGroupId
      HealthCheckGracePeriodSeconds: 60
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-auth-service'
        - Key: Environment
          Value: production

  # ============================================
  # Management Service
  # ============================================
  ManagementService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: management-dashboard-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ManagementServiceTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PublicSubnetIds
          SecurityGroups:
            - !Ref ECSSecurityGroupId
      HealthCheckGracePeriodSeconds: 60
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-management-service'
        - Key: Environment
          Value: production

  # ============================================
  # Auto Scaling for Auth Service
  # ============================================
  AuthServiceScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 3
      MinCapacity: 1
      ResourceId: !Sub 'service/${ECSCluster}/${AuthService.Name}'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  AuthServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${EnvironmentName}-auth-service-cpu-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AuthServiceScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

  # ============================================
  # CloudWatch Alarms
  # ============================================
  AuthServiceCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${EnvironmentName}-auth-service-high-cpu'
      AlarmDescription: Alert when Auth Service CPU is high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: !GetAtt AuthService.Name
        - Name: ClusterName
          Value: !Ref ECSCluster

  ManagementServiceCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${EnvironmentName}-management-service-high-cpu'
      AlarmDescription: Alert when Management Service CPU is high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: !GetAtt ManagementService.Name
        - Name: ClusterName
          Value: !Ref ECSCluster

Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${EnvironmentName}-ecs-cluster-name'

  ECSClusterArn:
    Description: ECS Cluster ARN
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub '${EnvironmentName}-ecs-cluster-arn'

  AuthServiceName:
    Description: Auth Service Name
    Value: !GetAtt AuthService.Name
    Export:
      Name: !Sub '${EnvironmentName}-auth-service-name'

  ManagementServiceName:
    Description: Management Service Name
    Value: !GetAtt ManagementService.Name
    Export:
      Name: !Sub '${EnvironmentName}-management-service-name'

  AuthServiceTaskDefinitionArn:
    Description: Auth Service Task Definition ARN
    Value: !Ref AuthServiceTaskDefinition
    Export:
      Name: !Sub '${EnvironmentName}-auth-task-def-arn'

  ManagementServiceTaskDefinitionArn:
    Description: Management Service Task Definition ARN
    Value: !Ref ManagementServiceTaskDefinition
    Export:
      Name: !Sub '${EnvironmentName}-management-task-def-arn'
