const JOB_STATUS = {
  PENDING: 'PENDING',
  DOWNLOADING: 'DOWNLOADING',
  PROCESSING: 'PROCESSING',
  UPLOADING: 'UPLOADING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

const ASSET_TYPES = {
  RANSCODE_1080: 'TRANSCODE_1080',
  TRANSCODE_720: 'TRANSCODE_720',
  TRANSCODE_480: 'TRANSCODE_480',
  GIF: 'GIF',
  THUMBNAIL: 'THUMBNAIL',
  METADATA_JSON: 'METADATA_JSON',
};

module.exports  = {
    JOB_STATUS,
    ASSET_TYPES
}