const JOB_STATUS = {
  PENDING: 'PENDING',
  DOWNLOADING: 'DOWNLOADING',
  PROCESSING: 'PROCESSING',
  UPLOADING: 'UPLOADING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

const ASSET_TYPES = {
  RANSCODE_1080: 'TRANSCODE_1080',
  TRANSCODE_720: 'TRANSCODE_720',
  TRANSCODE_480: 'TRANSCODE_480',
  GIF: 'GIF',
  THUMBNAIL: 'THUMBNAIL',
  METADATA_JSON: 'METADATA_JSON',
};

const SUPPORTED_FORMATS = ['1080p', '720p', '480p', 'gif'];
const MAX_FILE_SIZE = 100 * 1024 * 1024; // 100MB
const MAX_DURATION = 600; // 10 minutes

module.exports  = {
    JOB_STATUS,
    ASSET_TYPES,
    SUPPORTED_FORMATS,
    MAX_FILE_SIZE,
    MAX_DURATION
}