CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    input_source VARCHAR(1024),
    output_format VARCHAR(255),
    status ENUM('PENDING','DOWNLOADING','PROCESSING','UPLOADING','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
    progress INT DEFAULT 0,
    error_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS media_assets (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  job_id BIGINT NOT NULL,
  asset_type ENUM('TRANSCODE_1080','TRANSCODE_720','TRANSCODE_480','GIF','THUMBNAIL','METADATA_JSON') NOT NULL,
  path VARCHAR(1024) NOT NULL COMMENT 'File path or S3 URL',
  size_bytes BIGINT DEFAULT NULL COMMENT 'File size in bytes',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
  INDEX idx_job_id (job_id),
  INDEX idx_asset_type (asset_type)
);

INSERT INTO users (email, password) VALUES
('user@test.com', '$2b$10$rQ8S.ZfF5YZQQyV9r6p6sON7F3.5xVJqGf0LPCnUXvSqD7.6yW5Xy')
ON DUPLICATE KEY UPDATE email=email;

SELECT 'Database setup complete.' as status;
SELECT * FROM users;